<div class="imagewrap" style="width:500px;">
<img src="/assets/images/site-images/cathedral-rock-sedona-az.jpg" width="500" height="330" alt="Catheral Rock Sedona Arizona" />
<div class="imagedesc span-13">Photo courtesy <a href="http://www.redrockimages.com/" title="Red Rock Images">Larry Pollock</a></div>
</div>
<h2>Welcome to Sedona, Arizona</h2> 
   <h3>"The Heart of Red Rock Country"</h3> 
   <p>We encourage you to patronize local businesses for your shopping and service needs. There is a direct connection between shopping locally and the quality of life here. Sedona's police, fire, streets, parks, libraries and much more are funded through sales taxes generated by shoppers. By supporting local businesses, you can directly improve the quality of life in Sedona. -- <a href="http://www.sedonachamber.com/" title="Sedona Chamber of Commerce">Sedona Chamber of Commerce</a></p>
      
<table id="businessTable" class="tablesorter span-17" style="clear:both;">
	<thead><tr><th>Business Name</th><th>Business Owner</th><th>Category</th><th>Web</th><th>Photos</th><th>Videos</th><th>Specials</th></tr></thead>
		<?php foreach ($featured->result() as $row): ?>
            <tr>
                <td><a href="/site/business/<?=$row->id?>"><?=$row->busname?></a></td>
                <td><?=$row->busowner?></td>
                <td><a href="/site/categories/<?=$row->category?>"><?=$row->catname?></a></td>
                <td><a href="<?=$row->webaddress?>">Visit Site</a></td>
                <td>
					<?php if(isset($row->thumb)):?>
                    yes
                    <?php else:?>
                    no
                    <?php endif?>
                    
                </td>
                
                <td>
					<?php if(isset($row->title)):?>
                    yes
                    <?php else:?>
                    no
                    <?php endif?>
                    
                
                </td>
                <td>
					<?php if(isset($row->specname)):?>
                    yes
                    <?php else:?>
                    no
                    <?php endif?>
                    
                
                </td>
            </tr>
        <?php endforeach; ?>

</table>

<div id="pager" class="pager" style="margin-bottom:3em;">
	<form>
		<img src="/assets/images/pager/icons/first.png" class="first"/>
		<img src="/assets/images/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="/assets/images/pager/icons/next.png" class="next"/>
		<img src="/assets/images/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>

			<option value="20">20</option>
			<option value="30">30</option>
			<option  value="40">40</option>
		</select>
	</form>
</div>